spring:
  datasource:
    url: jdbc:mysql://182.92.175.167:3306/FoodBlog?useUnicode=true&characterEncoding=utf8
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  redis:
    host: 182.92.175.167
    port: 6379
    password: testredis

server:
  port: 8082

logging:
  level:
    org.springframework: error
