spring:
  datasource:
    url: jdbc:mysql://182.92.175.167:3306/FoodBlog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
  redis:
    host: 182.92.175.167
    port: 6379
    password: testredis
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


server:
  port: 8082

logging:
  level:
    org.springframework: error
